name: Docs Spellcheck

on:
  pull_request:
    paths: ["**/*.md"]
  push:
    branches: [main]
    paths: ["**/*.md"]

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install codespell
        run: |
          python -m pip install --upgrade pip
          pip install codespell

      - name: Run codespell on documentation
        run: codespell -q 3 Documentation_Testing_Manual.md
